table_sets:
  common:
    partitions:
      - leader:
          host: 127.0.0.8
          database: default_db
          username: normal_user
          password: secure_password
          timeout: 2
        followers: []
    readable:
      - zip_codes
      - rt_transactions
    writable:
      - users
      - entries

  realtime:
    partitions:
      - leader:
          host: 127.0.0.9
          database: realtime_db
          username: realtime_user
          password: realtime_password
          timeout: 1
        followers: []
    readable:
      - zip_codes
      - users
      - entries
    writable:
      - rt_transactions
